### ISSUE TITLE
Fails when performing liftover on opposite strand

### ISSUE THREAD

**Issue by winstonewert** [stjude-rust-labs/chainfile#3]
Chainfile:

```
chain 0 a 100 + 0 100 b 100 + 0 100 34
100
```

Code:
```
let from = Coordinate::try_new("a", 78, Strand::Negative)?;
let to = Coordinate::try_new("a", 13, Strand::Negative)?;

let interval = Interval::try_new(from, to)?;
dbg!(chain.liftover(&interval));
```

Result:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidInterval(MismatchedStrandDuringClamp(Positive, Negative))'
```

**Comment by claymcleod** [comment]
Hi there! Apologies for not seeing this until now. I've fixed this in https://github.com/stjude-rust-labs/chainfile/commit/bd4d7c2837bbecede6bcc9c20d983349a082fcc6. You can update to [v0.2.1](https://github.com/stjude-rust-labs/chainfile/releases/tag/v0.2.1) for the fix.

In short, the [`rust-lapper`](https://crates.io/crates/rust-lapper) crate is used behind the scenes to store liftover intervals. In the liftover machine, I failed to also ensure the strand matches before attempting the liftover. This, in turn, throws this strange error via other fail safes that had been built in to the interval struct. 

Instead, a `None` result should be returned here, as the chain file does not cover the interval being requested for liftover. That's now how the code behaves.

Thanks for the bug report!
